apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-defaults.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart-defaults.labels" . | nindent 4 }}
data:
  index.html: |-
    <!doctype html>
    <html>
      <head>
        <title>Welcome to your secure web page using Nginx</title>
      </head>
      <body>
        <p>This will be a secure web page at the end of the tutorial!</p>
      </body>
    </html>